version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: stevendumont/m1
    steps:
      - run: echo "Hi I'm on a Container Runner!"
workflows:
  build-workflow:
    jobs:
      - build
