version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: stevendumont/m1
    steps:
      - run: echo "Hi I'm on a Container Runner from build !"
  test:
    docker:
      - image: cimg/base:current
    resource_class: stevendumont/m1
    steps:
      - run: echo "Hi I'm on a Container Runner from test !"
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "20 0 * * *"
          filters:
            branches:
              only:
                - circleci-*
    jobs:
      - test
  build-workflow:
    jobs:
      - build
